//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWeb_LiceoExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaPlatillo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaPlatillo()
        {
            this.CategoriaPlatillo1 = new HashSet<CategoriaPlatillo>();
        }
    
        public int CategoriaPlatilloID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int CategoriaPlatilloPadreID { get; set; }
        public int PlatilloID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaPlatillo> CategoriaPlatillo1 { get; set; }
        public virtual CategoriaPlatillo CategoriaPlatillo2 { get; set; }
        public virtual Platillo Platillo { get; set; }
    }
}
