//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWeb_LiceoExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificadorPersona
    {
        public long IdentificadorPersonaID { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public long PersonaID { get; set; }
        public byte TipoIdentificadorPersonaID { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual TipoIdentificadorPersona TipoIdentificadorPersona { get; set; }
    }
}
