//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWeb_LiceoExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public System.Guid ID { get; set; }
        public long NoticiaID { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<long> LineaNoticiaID { get; set; }
        public Nullable<long> UsuarioID { get; set; }
        public byte[] Archivo { get; set; }
    
        public virtual LineaNoticia LineaNoticia { get; set; }
    }
}
