//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWeb_LiceoExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int ReservaID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public long PersonaID { get; set; }
        public long PlatilloDiaID { get; set; }
        public bool Estado { get; set; }
    
        public virtual PlatilloDia PlatilloDia { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
