//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWeb_LiceoExperimental
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public short TipoCambioID { get; set; }
        public decimal MontoCompra { get; set; }
        public decimal MontoVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte MonedaOrigenID { get; set; }
        public byte MonedaDestinoID { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
    }
}
